apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kube-express-deployment
  labels:
    app: express
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        imagePullPolicy: Never
        image: kube-express:1
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: kube-express-service
spec:
  selector:
    app: express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
